{"name": " -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0041ACD3+2075859]\n\tOrdinal0 [0x003AEE61+1633889]\n\tOrdinal0 [0x002AB7BD+571325]\n\tOrdinal0 [0x002DAC2F+764975]\n\tOrdinal0 [0x002DAE1B+765467]\n\tOrdinal0 [0x0030D0F2+970994]\n\tOrdinal0 [0x002F7364+881508]\n\tOrdinal0 [0x0030B56A+963946]\n\tOrdinal0 [0x002F7136+880950]\n\tOrdinal0 [0x002CFEFD+720637]\n\tOrdinal0 [0x002D0F3F+724799]\n\tGetHandleVerifier [0x006CEED2+2769538]\n\tGetHandleVerifier [0x006C0D95+2711877]\n\tGetHandleVerifier [0x004AA03A+521194]\n\tGetHandleVerifier [0x004A8DA0+516432]\n\tOrdinal0 [0x003B682C+1665068]\n\tOrdinal0 [0x003BB128+1683752]\n\tOrdinal0 [0x003BB215+1683989]\n\tOrdinal0 [0x003C6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User should be able to launch the browser", "status": "passed", "start": 1667453090308, "stop": 1667453138114}, {"name": "Then User should be able to enter homepage of pharmeasy application", "status": "passed", "start": 1667453138114, "stop": 1667453153088}, {"name": "When User should be able to click on medicine module", "status": "passed", "start": 1667453153088, "stop": 1667453175295}, {"name": "And User should be able to click on pincode", "status": "passed", "start": 1667453175296, "stop": 1667453175821}, {"name": "Then User should be able to enter \"577301\"", "status": "passed", "start": 1667453175823, "stop": 1667453177320}, {"name": "And User should be able to click on submit", "status": "passed", "start": 1667453177321, "stop": 1667453182578}, {"name": "Then User should be able to search for \"dolo\"", "status": "passed", "start": 1667453182579, "stop": 1667453182977}, {"name": "And User is able to click on search button", "status": "passed", "start": 1667453182977, "stop": 1667453183330}, {"name": "And User should be able to select the product", "status": "passed", "start": 1667453183331, "stop": 1667453187409}, {"name": "Then User should be able to select quantity", "status": "passed", "start": 1667453187410, "stop": 1667453187827}, {"name": "And User is able to click on view cart", "status": "passed", "start": 1667453187827, "stop": 1667453212145}, {"name": "And User is able to add delivery address", "status": "passed", "start": 1667453212146, "stop": 1667453212576}, {"name": "Then User is able to login with \"9008240114\"", "status": "passed", "start": 1667453212577, "stop": 1667453213378}, {"name": "And User is able to click on send otp", "status": "passed", "start": 1667453213378, "stop": 1667453233768}, {"name": "And User should be able to click on continue", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0041ACD3+2075859]\n\tOrdinal0 [0x003AEE61+1633889]\n\tOrdinal0 [0x002AB7BD+571325]\n\tOrdinal0 [0x002DAC2F+764975]\n\tOrdinal0 [0x002DAE1B+765467]\n\tOrdinal0 [0x0030D0F2+970994]\n\tOrdinal0 [0x002F7364+881508]\n\tOrdinal0 [0x0030B56A+963946]\n\tOrdinal0 [0x002F7136+880950]\n\tOrdinal0 [0x002CFEFD+720637]\n\tOrdinal0 [0x002D0F3F+724799]\n\tGetHandleVerifier [0x006CEED2+2769538]\n\tGetHandleVerifier [0x006C0D95+2711877]\n\tGetHandleVerifier [0x004AA03A+521194]\n\tGetHandleVerifier [0x004A8DA0+516432]\n\tOrdinal0 [0x003B682C+1665068]\n\tOrdinal0 [0x003BB128+1683752]\n\tOrdinal0 [0x003BB215+1683989]\n\tOrdinal0 [0x003C6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667453233769, "stop": 1667453264481}, {"name": "And User should be able to click on save", "status": "skipped", "start": 1667453264483, "stop": 1667453264483}], "parameters": [{"name": "pincode", "value": "577301"}, {}, {"name": "medicine", "value": "dolo"}, {}, {"name": "mobile_number", "value": "9008240114"}], "start": 1667453090304, "stop": 1667453264483, "uuid": "c579011b-c16e-4526-bbd4-873c9ab0a0d1", "historyId": "54fa58cd2d8d3eb0d8626091066c75f4", "fullName": "Medicine_module: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Medicine_module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}