{"name": " -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User should be able to launch the browser", "status": "passed", "start": 1667454791207, "stop": 1667454862320}, {"name": "Then User should be able to enter homepage of pharmeasy application", "status": "passed", "start": 1667454862321, "stop": 1667454876896}, {"name": "When User should be able to click on medicine module", "status": "passed", "start": 1667454876896, "stop": 1667454896687}, {"name": "And User should be able to click on pincode", "status": "passed", "start": 1667454896688, "stop": 1667454896866}, {"name": "Then User should be able to enter \"577301\"", "status": "passed", "start": 1667454896867, "stop": 1667454897507}, {"name": "And User should be able to click on submit", "status": "passed", "start": 1667454897508, "stop": 1667454902653}, {"name": "Then User should be able to search for \"dolo\"", "status": "passed", "start": 1667454902653, "stop": 1667454902924}, {"name": "And User is able to click on search button", "status": "passed", "start": 1667454902924, "stop": 1667454903140}, {"name": "And User should be able to select the product", "status": "passed", "start": 1667454903140, "stop": 1667454905612}, {"name": "Then User should be able to select quantity", "status": "passed", "start": 1667454905613, "stop": 1667454906179}, {"name": "And User is able to click on view cart", "status": "passed", "start": 1667454906180, "stop": 1667454917539}, {"name": "And User is able to add delivery address", "status": "passed", "start": 1667454917540, "stop": 1667454918165}, {"name": "Then User is able to login with \"9008240114\"", "status": "passed", "start": 1667454918165, "stop": 1667454918883}, {"name": "And User is able to click on send otp", "status": "passed", "start": 1667454918883, "stop": 1667454939582}, {"name": "And User should be able to click on continue", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667454939583, "stop": 1667454960039}, {"name": "And User should be able to click on save", "status": "skipped", "start": 1667454960041, "stop": 1667454960041}], "parameters": [{"name": "pincode", "value": "577301"}, {"name": "medicine", "value": "dolo"}, {"name": "mobile_number", "value": "9008240114"}], "start": 1667454791168, "stop": 1667454960041, "uuid": "7b9fb947-54f9-4ad2-9962-abd9c2bdaaa2", "historyId": "50ef04eccef7eba456cc3e3139deafee", "fullName": "Medicine_module: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Medicine_module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}