{"name": " -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User should be able to launch the browser", "status": "passed", "start": 1667454960268, "stop": 1667454999796}, {"name": "Then User should be able to enter homepage of pharmeasy application", "status": "passed", "start": 1667454999796, "stop": 1667455016791}, {"name": "When User should be able to click on medicine module", "status": "passed", "start": 1667455016791, "stop": 1667455031937}, {"name": "And User should be able to click on pincode", "status": "passed", "start": 1667455031938, "stop": 1667455032139}, {"name": "Then User should be able to enter \"572222\"", "status": "passed", "start": 1667455032140, "stop": 1667455032511}, {"name": "And User should be able to click on submit", "status": "passed", "start": 1667455032512, "stop": 1667455037698}, {"name": "Then User should be able to search for \"dolo\"", "status": "passed", "start": 1667455037699, "stop": 1667455037927}, {"name": "And User is able to click on search button", "status": "passed", "start": 1667455037929, "stop": 1667455038072}, {"name": "And User should be able to select the product", "status": "passed", "start": 1667455038072, "stop": 1667455040238}, {"name": "Then User should be able to select quantity", "status": "passed", "start": 1667455040238, "stop": 1667455040705}, {"name": "And User is able to click on view cart", "status": "passed", "start": 1667455040706, "stop": 1667455050100}, {"name": "And User is able to add delivery address", "status": "passed", "start": 1667455050100, "stop": 1667455050444}, {"name": "Then User is able to login with \"8217374794\"", "status": "passed", "start": 1667455050445, "stop": 1667455051262}, {"name": "And User is able to click on send otp", "status": "passed", "start": 1667455051263, "stop": 1667455071578}, {"name": "And User should be able to click on continue", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[text()=\"CONTINUE\"]\"}\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FFACD3+2075859]\n\tOrdinal0 [0x00F8EE61+1633889]\n\tOrdinal0 [0x00E8B7BD+571325]\n\tOrdinal0 [0x00EBAC2F+764975]\n\tOrdinal0 [0x00EBAE1B+765467]\n\tOrdinal0 [0x00EED0F2+970994]\n\tOrdinal0 [0x00ED7364+881508]\n\tOrdinal0 [0x00EEB56A+963946]\n\tOrdinal0 [0x00ED7136+880950]\n\tOrdinal0 [0x00EAFEFD+720637]\n\tOrdinal0 [0x00EB0F3F+724799]\n\tGetHandleVerifier [0x012AEED2+2769538]\n\tGetHandleVerifier [0x012A0D95+2711877]\n\tGetHandleVerifier [0x0108A03A+521194]\n\tGetHandleVerifier [0x01088DA0+516432]\n\tOrdinal0 [0x00F9682C+1665068]\n\tOrdinal0 [0x00F9B128+1683752]\n\tOrdinal0 [0x00F9B215+1683989]\n\tOrdinal0 [0x00FA6484+1729668]\n\tBaseThreadInitThunk [0x7675FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x776B7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x776B7B8E+238]\n\n", "trace": "  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pharmeasy_test.py\", line 85, in click_continue\n    context.driver.find_element(\"xpath\", '//button[text()=\"CONTINUE\"]').click()\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Adithya M M\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667455071579, "stop": 1667455091697}, {"name": "And User should be able to click on save", "status": "skipped", "start": 1667455091698, "stop": 1667455091698}], "parameters": [{"name": "pincode", "value": "572222"}, {"name": "medicine", "value": "dolo"}, {"name": "mobile_number", "value": "8217374794"}], "start": 1667454960226, "stop": 1667455091698, "uuid": "b0cebd86-800f-4a0e-8487-4e29e10c2b2d", "historyId": "c580f068a233b01f67b34083082963cf", "fullName": "Medicine_module: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Medicine_module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}